
@startuml PERT
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title Pert: Project Design of Single Numbering Network
map Start {
    ES => 0
    LS => 0
    EF => 0
    LF => 0
    TF => 0
    FF => 0
}
map A {
    ES => 0
    LS => 0
    EF => 2
    LF => 2
    TF => 0
    FF => 0
}
map B {
    ES => 0
    LS => 4
    EF => 3
    LF => 7
    TF => 4
    FF => 2
}
map C {
    ES => 2
    LS => 4
    EF => 5
    LF => 7
    TF => 2
    FF => 0
}
map D {
    ES => 2
    LS => 2
    EF => 5
    LF => 5
    TF => 0
    FF => 0
}
map E {
    ES => 5
    LS => 7
    EF => 7
    LF => 9
    TF => 2
    FF => 2
}
map F {
    ES => 5
    LS => 5
    EF => 9
    LF => 9
    TF => 0
    FF => 0
}
map G {
    ES => 5
    LS => 7
    EF => 8
    LF => 10
    TF => 2
    FF => 2
}
map H {
    ES => 9
    LS => 9
    EF => 10
    LF => 10
    TF => 0
    FF => 0
}
map End {
    ES => 10
    LS => 10
    EF => 10
    LF => 10
    TF => 0
    FF => 0
}
Start -[thickness=5]-> A
Start --> B
A --> C
A -[thickness=5]-> D
B --> E
C --> E
D -[thickness=5]-> F
D --> G
A --> H
E --> H
F -[thickness=5]-> H
G --> End
H -[thickness=5]-> End
@enduml