
@startuml PERT
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title Pert: Project Design of Double Numbering Network
map 0 {
    earliest start => 0
    latest start => 0
}
map End {
    earliest start => 12
    latest start => 12
}
map A {
    earliest start => 0
    latest start => 0
}
map B {
    earliest start => 0
    latest start => 4
}
map C {
    earliest start => 2
    latest start => 4
}
map D {
    earliest start => 2
    latest start => 2
}
map virtual_E {
    earliest start => 5
    latest start => 7
}
map E {
    earliest start => 5
    latest start => 7
}
map F {
    earliest start => 5
    latest start => 5
}
map virtual_G {
    earliest start => 9
    latest start => 9
}
map G {
    earliest start => 9
    latest start => 9
}
map virtual_H {
    earliest start => 9
    latest start => 11
}
map H {
    earliest start => 9
    latest start => 11
}
map virtual_End {
    earliest start => 12
    latest start => 12
}
0 -[thickness=5]-> A : A (Id=A, D=2, TF=0, FF=0)
0 --> B : B (Id=B, D=3, TF=4, FF=2)
A --> C : C (Id=C, D=3, TF=2, FF=0)
A -[thickness=5]-> D : D (Id=D, D=3, TF=0, FF=0)
B -[dashed]-> virtual_E
C -[dashed]-> virtual_E
virtual_E --> E : E (Id=E, D=2, TF=2, FF=2)
D -[thickness=5]-> F : F (Id=F, D=4, TF=0, FF=0)
E -[dashed]-> virtual_G
F -[dashed,thickness=5]-> virtual_G
virtual_G -[thickness=5]-> G : G (Id=G, D=3, TF=0, FF=0)
A -[dashed]-> virtual_H
E -[dashed]-> virtual_H
F -[dashed]-> virtual_H
virtual_H --> H : H (Id=H, D=1, TF=2, FF=2)
G -[dashed,thickness=5]-> virtual_End
H -[dashed]-> virtual_End
virtual_End -[thickness=5]-> End : End (Id=End, D=0, TF=0, FF=0)
@enduml