
@startuml PERT
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title Pert: Project Design of Single Numbering Network
map Start {
    ES => 0
    LS => 0
    EF => 0
    LF => 0
    TF => 0
    FF => 0
}
map A {
    ES => 0
    LS => 1
    EF => 5
    LF => 6
    TF => 1
    FF => 0
}
map B {
    ES => 0
    LS => 0
    EF => 10
    LF => 10
    TF => 0
    FF => 0
}
map C {
    ES => 0
    LS => 5
    EF => 11
    LF => 16
    TF => 5
    FF => 3
}
map D {
    ES => 10
    LS => 12
    EF => 14
    LF => 16
    TF => 2
    FF => 0
}
map E {
    ES => 5
    LS => 6
    EF => 9
    LF => 10
    TF => 1
    FF => 1
}
map F {
    ES => 14
    LS => 16
    EF => 29
    LF => 31
    TF => 2
    FF => 2
}
map G {
    ES => 10
    LS => 10
    EF => 31
    LF => 31
    TF => 0
    FF => 0
}
map H {
    ES => 10
    LS => 16
    EF => 45
    LF => 51
    TF => 6
    FF => 6
}
map I {
    ES => 10
    LS => 11
    EF => 35
    LF => 36
    TF => 1
    FF => 0
}
map J {
    ES => 35
    LS => 36
    EF => 50
    LF => 51
    TF => 1
    FF => 1
}
map K {
    ES => 31
    LS => 31
    EF => 51
    LF => 51
    TF => 0
    FF => 0
}
map End {
    ES => 51
    LS => 51
    EF => 51
    LF => 51
    TF => 0
    FF => 0
}
Start --> A
Start -[thickness=5]-> B
Start --> C
B --> D
A --> E
C --> F
D --> F
B -[thickness=5]-> G
E --> G
B --> H
E --> H
B --> I
E --> I
F --> J
G --> J
I --> J
F --> K
G -[thickness=5]-> K
H --> End
J --> End
K -[thickness=5]-> End
@enduml