
@startuml PERT
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title Pert: Project Design of Single Numbering Network
map Start {
    ES => 0
    LS => 0
    EF => 0
    LF => 0
    TF => 0
    FF => 0
}
map A {
    ES => 0
    LS => 0
    EF => 3
    LF => 3
    TF => 0
    FF => 0
}
map B {
    ES => 3
    LS => 5
    EF => 7
    LF => 9
    TF => 2
    FF => 0
}
map C {
    ES => 3
    LS => 3
    EF => 9
    LF => 9
    TF => 0
    FF => 0
}
map D {
    ES => 9
    LS => 9
    EF => 17
    LF => 17
    TF => 0
    FF => 0
}
map E {
    ES => 7
    LS => 12
    EF => 12
    LF => 17
    TF => 5
    FF => 5
}
map F {
    ES => 9
    LS => 15
    EF => 13
    LF => 19
    TF => 6
    FF => 4
}
map G {
    ES => 17
    LS => 17
    EF => 23
    LF => 23
    TF => 0
    FF => 0
}
map H {
    ES => 17
    LS => 19
    EF => 21
    LF => 23
    TF => 2
    FF => 2
}
map I {
    ES => 23
    LS => 23
    EF => 28
    LF => 28
    TF => 0
    FF => 0
}
map End {
    ES => 28
    LS => 28
    EF => 28
    LF => 28
    TF => 0
    FF => 0
}
Start -[thickness=5]-> A
A --> B
A -[thickness=5]-> C
B --> D
C -[thickness=5]-> D
B --> E
C --> F
D -[thickness=5]-> G
E --> G
D --> H
F --> H
G -[thickness=5]-> I
H --> I
I -[thickness=5]-> End
@enduml