
@startuml PERT
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title Pert: Project Design of Double Numbering Network
map 0 {
    earliest start => 0
    latest start => 0
}
map End {
    earliest start => 28
    latest start => 28
}
map A {
    earliest start => 0
    latest start => 0
}
map B {
    earliest start => 3
    latest start => 5
}
map C {
    earliest start => 3
    latest start => 3
}
map virtual_D {
    earliest start => 9
    latest start => 9
}
map D {
    earliest start => 9
    latest start => 9
}
map E {
    earliest start => 7
    latest start => 12
}
map F {
    earliest start => 9
    latest start => 15
}
map virtual_G {
    earliest start => 17
    latest start => 17
}
map G {
    earliest start => 17
    latest start => 17
}
map virtual_H {
    earliest start => 17
    latest start => 19
}
map H {
    earliest start => 17
    latest start => 19
}
map virtual_I {
    earliest start => 23
    latest start => 23
}
map I {
    earliest start => 23
    latest start => 23
}
0 -[thickness=5]-> A : A (Id=A, D=3, TF=0, FF=0)
A --> B : B (Id=B, D=4, TF=2, FF=0)
A -[thickness=5]-> C : C (Id=C, D=6, TF=0, FF=0)
B -[dashed]-> virtual_D
C -[dashed,thickness=5]-> virtual_D
virtual_D -[thickness=5]-> D : D (Id=D, D=8, TF=0, FF=0)
B --> E : E (Id=E, D=5, TF=5, FF=5)
C --> F : F (Id=F, D=4, TF=6, FF=4)
D -[dashed,thickness=5]-> virtual_G
E -[dashed]-> virtual_G
virtual_G -[thickness=5]-> G : G (Id=G, D=6, TF=0, FF=0)
D -[dashed]-> virtual_H
F -[dashed]-> virtual_H
virtual_H --> H : H (Id=H, D=4, TF=2, FF=2)
G -[dashed,thickness=5]-> virtual_I
H -[dashed]-> virtual_I
virtual_I -[thickness=5]-> I : I (Id=I, D=5, TF=0, FF=0)
I -[thickness=5]-> End : End (Id=End, D=0, TF=0, FF=0)
@enduml